### ISSUE TITLE
Bungeecord dont' get pinged with Pufferpanel (no docker)

### ISSUE THREAD

**Issue by Malachiel87** [PufferPanel/Scales#70] opened 2016-01-28 13:32 UTC
Hi i just upgraded to pufferpanel 0.8.5 and scales 0.2.4 with success and disabled dockers, changed all server ip and ql and config from docker ip to 127.0.0.1, all server look fine, but the bungeecord is not pinged in pufferpanel (red dot) (ip 0.0.0.0) and only console is working, but no ram/cpu/player usage are show

**Comment by phlupp** [comment] 2016-03-15 13:28
The problem is that the output from bungee has changed. On `../scales/lib/plugins/bungeecord/config.json` scales is waiting for "[INFO] Listening on " but BungeeCords output is "[INFORMATION] Listening on ".

Change

> "trigger": {
>         "started": "[INFO] Listening on "
>     },

to

> "trigger": {
>         "started": "[INFORMATION] Listening on "
>     },

and restart scales,  now it works.

@puffrfish can you please change the file for next release

**Comment by Malachiel87** [comment] 2016-03-15 13:34
is working! i created the pull :;3

**Comment by phlupp** [comment] 2016-03-15 13:37
ups i also created a pull ... sorry ;-)

**Comment by Malachiel87** [comment] 2016-03-15 13:40
lol i delete mine so

**Comment by Malachiel87** [comment] 2016-03-15 13:43
just re-open it, is a your fix :3

**Comment by phlupp** [comment] 2016-03-15 13:47
Done ;)

**Comment by puffrfish** [comment] 2016-03-15 14:33
Will this break older BungeeCord servers or has this issue always existed?

**Comment by phlupp** [comment] 2016-03-15 14:39
it think the output from bungee has changend, but i don't know when, i think that was very old version.

the problem is since I use PP (about 2 years)

**Comment by phlupp** [comment] 2016-03-15 14:59
now i saw that it doesnt change generally, if you look to the actual issue reporting from bungee the people post logs with [INFO] tag. I don't know why is shown different.

@xion87 what are your system prefernces ?

I am using debian jessy with Oracle Java 8u74

**Comment by puffrfish** [comment] 2016-03-15 15:01
Yes, from a brief check it does depend on the Java version. Ubuntu 14.04 OpenJDK 1.7 prints [INFO]

**Comment by phlupp** [comment] 2016-03-15 15:04
ok, can there be used wildcard, regex or something?

**Comment by Malachiel87** [comment] 2016-03-15 15:07
Using Ubuntu 14 java 8 here..

**Comment by Malachiel87** [comment] 2016-03-15 15:13
my bungee is formated like this (i am italian)
21:15:43 [INFORMAZIONI] [/151.64.85.28:29994] <-> InitialHandler has connected
21:15:43 [INFORMAZIONI] [/87.12.206.246:51024] <-> InitialHandler has connected
21:15:43 [INFORMAZIONI] [/2.38.134.78:54210] <-> InitialHandler has connected

**Comment by phlupp** [comment] 2016-03-16 08:49
ok, it seems that java 8 outputs in local spelling. My Bungee prints

> 09:50:24 [INFORMATION] [/192.168.178.34:53132] <-> InitialHandler has connected
> 09:50:34 [INFORMATION] [/192.168.178.34:53133] <-> InitialHandler has connected

(german)

**Comment by phlupp** [comment] 2016-03-16 09:40
if you add to the Startup Command `-Duser.language=en`

`-Duser.language=en -Xms${memory}M -Xmx${memory}M -server -jar ${jar}`

the output changes to english language:

> 10:37:04 [INFO] Listening on /192.168.178.34:25565
> 10:37:04 [INFO] Started query on /192.168.178.34:25565>

then it works with scales default config.

I dont know how to solve this permanently, it would be nice if the console output can be like local language, but then you have to edit the bungee config. maybe there can be added some intelligence to scales. It is possible to read the locale setting from java:

`java -XshowSettings:locale`

> Locale settings:
>     default locale = Deutsch
>     default display locale = Deutsch (Deutschland)
>     default format locale = Deutsch (Deutschland)
>     available locales = , ar, ar_AE, ar_BH, ar_DZ, ar_EG, ar_IQ, ar_JO,
>         ar_KW, ar_LB, ar_LY, ar_MA, ar_OM, ar_QA, ar_SA, ar_SD,
>         ar_SY, ar_TN, ar_YE, be, be_BY, bg, bg_BG, ca,
>         ca_ES, cs, cs_CZ, da, da_DK, de, de_AT, de_CH,
>         de_DE, de_GR, de_LU, el, el_CY, el_GR, en, en_AU,
>         en_CA, en_GB, en_IE, en_IN, en_MT, en_NZ, en_PH, en_SG,
>         en_US, en_ZA, es, es_AR, es_BO, es_CL, es_CO, es_CR,
>         es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI,
>         es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE,
>         et, et_EE, fi, fi_FI, fr, fr_BE, fr_CA, fr_CH,
>         fr_FR, fr_LU, ga, ga_IE, hi, hi_IN, hr, hr_HR,
>         hu, hu_HU, in, in_ID, is, is_IS, it, it_CH,
>         it_IT, iw, iw_IL, ja, ja_JP, ja_JP_JP_#u-ca-japanese, ko, ko_KR,
>         lt, lt_LT, lv, lv_LV, mk, mk_MK, ms, ms_MY,
>         mt, mt_MT, nl, nl_BE, nl_NL, no, no_NO, no_NO_NY,
>         pl, pl_PL, pt, pt_BR, pt_PT, ro, ro_RO, ru,
>         ru_RU, sk, sk_SK, sl, sl_SI, sq, sq_AL, sr,
>         sr_BA, sr_BA_#Latn, sr_CS, sr_ME, sr_ME_#Latn, sr_RS, sr_RS_#Latn, sr__#Latn,
>         sv, sv_SE, th, th_TH, th_TH_TH_#u-nu-thai, tr, tr_TR, uk,
>         uk_UA, vi, vi_VN, zh, zh_CN, zh_HK, zh_SG, zh_TW

in my case Deutsch (german)

**Comment by LordRalex** [comment] 2016-07-29 17:56
I am closing this issue, as the new daemon is not going down this road of reading logs for arbitrary lines. We are instead just going to assume that a server is up when it is started, since these hooks are very easy to break (as we have seen).

**Closed as completed by LordRalex** 2016-07-29 17:56 UTC
Labels: bug, wontfix
