### ISSUE TITLE
Failed to Bind Port

### ISSUE THREAD

**Issue by DDynamic** [PufferPanel/Scales#19] opened 2015-05-10 02:19 UTC
Hi,
When scales kills a server, sometimes it doesn't completely kill the process. In order to completely fix this, when scales kills a server it needs to run this:

```
sh killport 12345
```

(Assuming you have `wget https://raw.github.com/abdennour/miscs.sh/master/killport` installed.

**Comment by DaneEveritt** [comment] 2015-05-10 02:20
You have another Scales instance running on the server already.

**Comment by Dylan3304** [comment] 2015-05-10 02:20
@DaneEveritt It is not that error, I forgot to type it in.

**Comment by DaneEveritt** [comment] 2015-05-10 02:24
Are you talking about individual servers that Scales runs, or the Scales process?

**Comment by DDynamic** [comment] 2015-05-10 02:42
Individual servers.

**Comment by DaneEveritt** [comment] 2015-05-10 02:46
Souldn't be happening unless the servers themselves aren't being killed properly. I haven't been able to reproduce this at all, and killing the server process should be clearing up and bound ports. Are you able to kill the server a second time at all, sometimes it just get a bit glitched.

Also, what do the Scales logs say? If it wasn't run as verbose I need you to run it as so until this bug happens again and then provide those logs.

**Comment by LordRalex** [comment] 2015-06-25 18:07
Closing this since the root issue is being tackled here: https://github.com/PufferPanel/Scales/issues/22

**Closed as completed by LordRalex** 2015-06-25 18:07 UTC
